services:
  # FastAPI backend
  - type: web
    name: nexa-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://krishusharma787_db_user:MfGdEcQbfT0WfSqo@nexa.mtlyboj.mongodb.net/nexa?retryWrites=true&w=majority&appName=Nexa
      - key: DELIVERY_LAT
        value: "19.1081783"
      - key: DELIVERY_LNG
        value: "72.8476666"
      - key: DELIVERY_PINCODE
        value: "400057"
      - key: RENDER_URL
        value: "https://nexa-2zks.onrender.com"
      - key: SWIGGY_SWR
        sync: false
      - key: SWIGGY_DEVICE_ID
        sync: false
      - key: SWIGGY_SESSION_TID
        sync: false
      - key: SWIGGY_WAF_TOKEN
        sync: false
      - key: ZOMATO_PHPSESSID
        sync: false
      - key: ZOMATO_CSRF
        sync: false
      - key: ZOMATO_AK_BMSC
        sync: false
      - key: ZOMATO_ABCK
        sync: false
